### ISSUE TITLE
index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by BlinkyStitt** [llamanodes/realistic-web3-rpc-requests#1]
```
% python3 -m src                 
hello, world!
head_block: 16038984
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/bryan/code/realistic-web3-rpc-requests/src/__main__.py", line 21, in <module>
    exit_code = asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/bryan/code/realistic-web3-rpc-requests/src/__main__.py", line 11, in main
    await asyncio.gather(
  File "/Users/bryan/code/realistic-web3-rpc-requests/src/all_token_transfers.py", line 30, in example
    holdings = await get_holdings(fei_addr, fei_deploy_block, head_block)
  File "/Users/bryan/code/realistic-web3-rpc-requests/src/all_token_transfers.py", line 7, in get_holdings
    transfers = await evm.async_get_erc20_transfers(
  File "/Users/bryan/code/realistic-web3-rpc-requests/venv/lib/python3.10/site-packages/ctc/evm/erc20_utils/erc20_events.py", line 59, in async_get_erc20_transfers
    transfers = await event_utils.async_get_events(
  File "/Users/bryan/code/realistic-web3-rpc-requests/venv/lib/python3.10/site-packages/ctc/evm/event_utils/event_crud.py", line 91, in async_get_events
    events = await backend_utils.async_run_on_backend(
  File "/Users/bryan/code/realistic-web3-rpc-requests/venv/lib/python3.10/site-packages/ctc/toolbox/backend_utils/backend_crud.py", line 61, in async_run_on_backend
    return await function(**function_kwargs)
  File "/Users/bryan/code/realistic-web3-rpc-requests/venv/lib/python3.10/site-packages/ctc/evm/event_utils/event_crud.py", line 220, in async_download_events
    if start_block < block_range[0]:
IndexError: index 0 is out of bounds for axis 0 with size 0
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x106365e40>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x106a11300>, 569056.295356875)]']
connector: <aiohttp.connector.TCPConnector object at 0x106365ed0>
```

**Comment by BlinkyStitt** [comment]
This happens during this code:

```
    transfers = await evm.async_get_erc20_transfers(
        token="0x956f47f50a910163d8bf957cf5846d573e7f87ca",
        event_name="Transfer",
    )
```
